# Generated by Django 4.0.4 on 2022-06-01 07:39

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shared.mixins.model_utils
import shared.mixins.views_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='category name', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='name')),
                ('slug', models.SlugField(blank=True, help_text='used to generate URL', null=True, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
            bases=(shared.mixins.views_mixins.CurrentSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(help_text='news headline', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='headline')),
                ('slug', models.SlugField(blank=True, help_text='used to generate URL', unique=True)),
                ('content', ckeditor.fields.RichTextField(help_text='the content of the article', verbose_name='content')),
                ('preview_image', models.ImageField(help_text='article preview image', upload_to='news_preview_images/%Y/%m/%d', verbose_name='article preview')),
                ('img_alt', models.CharField(blank=True, help_text='text to be loaded in case of image loss', max_length=100, verbose_name='image alternative')),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='rating news', max_digits=2, verbose_name='rating')),
                ('likes', models.PositiveIntegerField(default=0, help_text='number of news ratings', verbose_name='likes')),
                ('views', models.PositiveIntegerField(default=0, help_text='number of news views', verbose_name='views')),
                ('author', models.ForeignKey(help_text='author of news', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(help_text='category of article', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'news',
                'verbose_name_plural': 'News',
                'ordering': ['updated'],
            },
            bases=(models.Model, shared.mixins.views_mixins.CurrentSlugMixin, shared.mixins.model_utils.ImageNameMixins),
        ),
    ]
