# Generated by Django 4.0.5 on 2022-06-07 11:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(help_text='category of news', null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='the content of the news', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(help_text='news preview image', upload_to='news_preview_images/%Y/%m/%d', verbose_name='news preview'),
        ),
    ]
