# Generated by Django 4.0.5 on 2022-06-07 11:24

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shared.mixins.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_alter_news_category_alter_news_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], decimal_places=0, default=1, help_text='news grade', max_digits=1, verbose_name='score')),
                ('status', models.CharField(choices=[('p', 'published'), ('b', 'blocked')], default='p', help_text='status of comment', max_length=1, verbose_name='status')),
                ('author', models.ForeignKey(help_text='author of score', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('news', models.ForeignKey(help_text='author of score', on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='article')),
            ],
            options={
                'verbose_name': 'score',
                'verbose_name_plural': 'Scores',
                'ordering': ['news', '-created'],
            },
            bases=(models.Model, shared.mixins.model_utils.ScoreMixins),
        ),
        migrations.CreateModel(
            name='LikeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'Likes',
                'ordering': ['news', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', ckeditor.fields.RichTextField(help_text='message (comment) of news', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='message')),
                ('status', models.CharField(choices=[('p', 'published'), ('b', 'blocked')], default='p', help_text='status of comment', max_length=1, verbose_name='status')),
                ('author', models.ForeignKey(help_text='author of comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('news', models.ForeignKey(help_text='commented news', on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='news')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['news', '-created'],
            },
        ),
    ]
